global:
  exporters:
    e1:
      format: "text"
      to: "stdout"
    e2:
      format: "json"
      to: "file://tmp/github-perf.json"

SIFT-fp32:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build"
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"fp32","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":40}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index_fp32"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: false


SIFT-pq:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build"
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"pq","max_degree":40,"ef_construction":400,"base_pq_dim": 32,"precise_quantization_type":"fp32","use_reorder":true}}'
    search_params: '{"hgraph":{"ef_search":57}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index_pq"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: false

SIFT-pqfs:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build"
    index_name: "ivf"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param": {
            "buckets_count": 50,
            "partition_strategy_type": "ivf",
            "ivf_train_type": "kmeans",
            "base_quantization_type": "pqfs",
            "precise_quantization_type": "fp32",
            "use_reorder": true,
            "base_pq_dim": 32,
            "precise_io_type": "async_io",
            "precise_file_path": "./precise_codes"
        }}'
    search_params: '{"ivf": {
            "scan_buckets_count": 10
        }}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index_pqfs"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: false

SIFT-ivfpq:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build"
    index_name: "ivf"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param": {
            "buckets_count": 50,
            "partition_strategy_type": "ivf",
            "ivf_train_type": "kmeans",
            "base_quantization_type": "pq",
            "precise_quantization_type": "fp32",
            "use_reorder": true,
            "base_pq_dim": 32
        }}'
    search_params: '{"ivf": {
            "scan_buckets_count": 20
        }}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index_ivfpq"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: false

SIFT-rabitq:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build"
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"rabitq","max_degree":32,"ef_construction":400,"precise_quantization_type":"fp32","use_reorder":true,"rabitq_bits_per_dim_query":32}}'
    search_params: '{"hgraph":{"ef_search":48}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index_rabitq"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: false

SIFT-sq8:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build"
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"sq8","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":44}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index_sq8"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: false

SIFT-sq8_uniform:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build"
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"sq8_uniform","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":44}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index_sq8_uniform"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: false