# FP32 Performance Test Configuration

global:
  exporters:
    e1:
      format: "text"
      to: "stdout"
    e2:
      format: "json"
      to: "file://tmp/github-perf.json"

SIFT-fp32:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "search"
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"fp32","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":40}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index_fp32"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: false