# SQ8 Performance Test Configuration

global:
  exporters:
    e1:
      format: "text"
      to: "stdout"
    e2:
      format: "json"
      to: "file://tmp/github-perf.json"

GIST-sq8:
    datapath: "/tmp/data/gist-960-euclidean.hdf5"
    type: "build,search"
    index_name: "hgraph"
    create_params: '{"dim":960,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"sq8","max_degree":96,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":120}}'
    index_path: "/tmp/gist-960-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: true
