# BF16 Performance Test Configuration

global:
  exporters:
    e1:
      format: "text"
      to: "stdout"
    e2:
      format: "json"
      to: "file://tmp/github-perf.json"

SIFT-bf16:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search"
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"bf16","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":48}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: true

DeepImage-bf16:
    datapath: "/tmp/data/deep-image-96-angular.hdf5"
    type: "build,search"
    index_name: "hgraph"
    create_params: '{"dim":96,"dtype":"float32","metric_type":"cosine","index_param":{"base_quantization_type":"bf16","max_degree":64,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":66}}'
    index_path: "/tmp/deep-image-96-angular/index/hgraph_index"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: true



GloVe-bf16:
    datapath: "/tmp/data/glove-100-angular.hdf5"
    type: "build,search"
    index_name: "hgraph"
    create_params: '{"dim":100,"dtype":"float32","metric_type":"cosine","index_param":{"base_quantization_type":"bf16","max_degree":80,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":220}}'
    index_path: "/tmp/glove-100-angular/index/hgraph_index"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: true

NYTimes-bf16:
    datapath: "/tmp/data/nytimes-256-angular.hdf5"
    type: "build,search"
    index_name: "hgraph"
    create_params: '{"dim":256,"dtype":"float32","metric_type":"cosine","index_param":{"base_quantization_type":"bf16","max_degree":80,"ef_construction":300}}'
    search_params: '{"hgraph":{"ef_search":132}}'
    index_path: "/tmp/nytimes-256-angular/index/hgraph_index"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: true