# GitHub-hosted runners provide 16 GB Memory and 14 GB Storage, which can only test some small datasets
# https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

global:
  exporters:
    e1: # give a name you like, will not be used
      format: "text"
      to: "stdout"
    e2:
      format: "json"
      to: "file://tmp/github-perf.json"

SIFT-fp32:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"fp32","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":29}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: true

SIFT-fp16:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"fp16","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":29}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: true
  
SIFT-bf16:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"bf16","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":29}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: true

SIFT-sq8:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"sq8","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":29}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: true

SIFT-sq8_uniform:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"sq8_uniform","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":29}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: true

SIFT-sq4:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"sq4","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":29}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: true

SIFT-sq4_uniform:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"sq4_uniform","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":29}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: true

SIFT-pq:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"pq","max_degree":32,"ef_construction":400,"base_pq_dim": 32}}'
    search_params: '{"hgraph":{"ef_search":29}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: true

SIFT-pqfs:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"pqfs","max_degree":32,"ef_construction":400,"base_pq_dim": 32}}'
    search_params: '{"hgraph":{"ef_search":29}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: true

SIFT-rabitq:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"rabitq","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":29}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
    delete_index_after_search: true

