# PQ Performance Test Configuration

global:
  exporters:
    e1:
      format: "text"
      to: "stdout"
    e2:
      format: "json"
      to: "file://tmp/github-perf.json"

SIFT-pq:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "search"
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"pq","max_degree":40,"ef_construction":400,"base_pq_dim": 32,"precise_quantization_type":"fp32","use_reorder":true}}'
    search_params: '{"hgraph":{"ef_search":57}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index_pq"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: true