# RABITQ Performance Test Configuration

global:
  exporters:
    e1:
      format: "text"
      to: "stdout"
    e2:
      format: "json"
      to: "file://tmp/github-perf.json"

SIFT-rabitq:
    datapath: "/tmp/data/sift-128-euclidean.hdf5"
    type: "build,search"
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"rabitq","max_degree":32,"ef_construction":400,"precise_quantization_type":"fp32","use_reorder":true,"rabitq_bits_per_dim_query":32}}'
    search_params: '{"hgraph":{"ef_search":48}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: true



GloVe-rabitq:
    datapath: "/tmp/data/glove-100-angular.hdf5"
    type: "build,search"
    index_name: "hgraph"
    create_params: '{"dim":100,"dtype":"float32","metric_type":"cosine","index_param":{"base_quantization_type":"rabitq","max_degree":96,"ef_construction":400,"precise_quantization_type":"fp32","use_reorder":true,"rabitq_bits_per_dim_query":32}}'
    search_params: '{"hgraph":{"ef_search":220}}'
    index_path: "/tmp/glove-100-angular/index/hgraph_index"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: true

NYTimes-rabitq:
    datapath: "/tmp/data/nytimes-256-angular.hdf5"
    type: "build,search"
    index_name: "hgraph"
    create_params: '{"dim":256,"dtype":"float32","metric_type":"cosine","index_param":{"base_quantization_type":"rabitq","max_degree":96,"ef_construction":300,"precise_quantization_type":"fp32","use_reorder":true,"rabitq_bits_per_dim_query":32}}'
    search_params: '{"hgraph":{"ef_search":132}}'
    index_path: "/tmp/nytimes-256-angular/index/hgraph_index"
    topk: 10
    search_mode: "knn"
    range: 0.5
    delete_index_after_search: true