# base image
FROM ubuntu:22.04

# update and install basic deps
RUN apt update && apt install -y wget gpg sudo


# install build tools
RUN apt install -y git g++ cmake ninja-build gdb ccache build-essential lcov gfortran
RUN apt install -y clang-15 clangd-15 clang-format-15 python3-pip
RUN ln -s /usr/bin/clang-format-15 /usr/bin/clang-format

# install vsag deps
RUN apt install -y python3-dev libomp-15-dev libaio-dev libcurl4-openssl-dev