"""
Lightweight runtime version resolution for pyvsag.

Preference order:
1. Explicit environment overrides (PYVSAG_VERSION / VSAG_VERSION).
2. Version generated by setuptools_scm and written to _generated_version.py.
3. Installed package metadata (importlib.metadata).
4. Local git describe output (mirrors cmake/GenerateVersionHeader.cmake).
5. Safe fallback "0.0.0.dev0".
"""

from __future__ import absolute_import

import os
import pathlib
import re
import subprocess
try:  # Python >=3.8
    from importlib.metadata import PackageNotFoundError, version as _metadata_version
except ImportError:  # Python 3.6-3.7
    from importlib_metadata import PackageNotFoundError, version as _metadata_version  # type: ignore

_RE_GIT_DESCRIBE = re.compile(
    r"""
    ^v?
    (?P<tag>[0-9][0-9A-Za-z\.\-_]*)
    (?:-(?P<distance>\d+)-g(?P<commit>[0-9a-f]+))?
    (?P<dirty>-dirty)?
    $
    """,
    re.VERBOSE,
)


def _normalize(raw):
    if not raw:
        return None
    value = raw.strip()
    if not value:
        return None
    if value[0] in ("v", "V"):
        value = value[1:]
    return value.replace("_", ".")


def _version_from_env():
    for key in ("PYVSAG_VERSION", "VSAG_VERSION"):
        resolved = _normalize(os.environ.get(key))
        if resolved:
            return resolved
    return None


def _version_from_generated():
    try:
        from . import _generated_version  # type: ignore
    except Exception:
        return None
    return getattr(_generated_version, "__version__", None)


def _version_from_metadata():
    try:
        return _metadata_version("pyvsag")
    except PackageNotFoundError:
        return None


def _pep440_from_git(describe):
    match = _RE_GIT_DESCRIBE.match(describe.strip())
    if not match:
        return None
    tag = _normalize(match.group("tag"))
    if not tag:
        return None
    distance = match.group("distance")
    if not distance:
        return tag
    suffix = ".dev{0}".format(distance)
    return tag + suffix


def _version_from_git():
    repo_root = pathlib.Path(__file__).resolve().parents[2]
    if not (repo_root / ".git").exists():
        return None
    cmd = ["git", "describe", "--tags", "--always", "--dirty", "--match", "v*"]
    try:
        output = subprocess.check_output(
            cmd,
            cwd=str(repo_root),
            stderr=subprocess.DEVNULL,
            universal_newlines=True,
        ).strip()
    except Exception:
        return None
    return _pep440_from_git(output)


def _resolve_version():
    for resolver in (
        _version_from_env,
        _version_from_generated,
        _version_from_metadata,
        _version_from_git,
    ):
        value = resolver()
        if value:
            return value
    return "0.0.0.dev0"


__version__ = _resolve_version()

__all__ = ["__version__"]

