name: Build Wheels

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            arch: x86_64
            runner: ubuntu-latest
          - os: ubuntu-latest
            arch: aarch64
            runner: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for setuptools_scm

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        with:
          package-dir: python
        env:
          # Tell cibuildwheel to build for the specific architecture
          CIBW_ARCHS: ${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl