name: Build Wheels

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for setuptools_scm

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        with:
          package-dir: python
        env:
          # Tell cibuildwheel to build for the specific architecture
          CIBW_ARCHS: ${{ matrix.arch }}
          # Run this script inside the manylinux container to install dependencies
          CIBW_BEFORE_ALL: |
            set -euo pipefail
            # Install development tools and other dependencies
            yum install -y wget gcc-c++ cmake ninja-build ccache gfortran libaio-devel libcurl-devel
            # Set up Intel MKL repository
            tee /etc/yum.repos.d/oneAPI.repo << EOF
            [oneAPI]
            name=Intel oneAPI repository
            baseurl=https://yum.repos.intel.com/oneapi
            enabled=1
            gpgcheck=1
            repo_gpgcheck=1
            gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
            EOF
            # Install Intel MKL
            yum install -y intel-oneapi-mkl-devel

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl