name: Build Wheels
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for setuptools_scm

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        with:
          package-dir: python
        env:
          # Tell cibuildwheel to build for the specific architecture
          CIBW_ARCHS: ${{ matrix.arch }}
          
          # Specify which Python versions to build
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
          
          # Skip PyPy and musllinux builds
          CIBW_SKIP: "pp* *-musllinux*"
          
          # Use a newer manylinux image that doesn't rely on CentOS 7
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014

          CIBW_BEFORE_ALL: |
            # Fix CentOS 7 repos
            sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*.repo
            sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo
  
            # Fix aarch64 specific issues
            if [[ "$(uname -m)" == "aarch64" ]]; then
            rm -f /etc/yum.repos.d/CentOS-SCLo-*.repo
            fi
  
            yum clean all
            
            # Install development tools
            yum install -y gcc gcc-c++ gcc-gfortran python3-devel
            
            # Install other dependencies
            yum install -y libaio-devel libcurl-devel ca-certificates
            
            # Install Intel MKL (only for x86_64)
            if [[ "$(uname -m)" == "x86_64" ]]; then
              yum-config-manager --add-repo https://yum.repos.intel.com/mkl/setup/intel-mkl.repo
              rpm --import https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
              yum install -y intel-mkl-64bit-2020.0-088
            fi
            
            # For OpenMP, use the standard package instead of alibaba-specific ones
            yum install -y libgomp

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error