name: Build Wheels

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-22.04-arm
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for setuptools_scm
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        with:
          package-dir: python
        env:
          # Tell cibuildwheel to build for the specific architecture
          CIBW_ARCHS: ${{ matrix.arch }}
          
          # Specify which Python versions to build
          CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-* cp310-* cp311-* cp312-*"
          
          # Skip PyPy and musllinux builds
          CIBW_SKIP: "pp* *-musllinux*"
          
          # Run this script inside the manylinux container to install dependencies
          CIBW_BEFORE_ALL: |
           # install python3-devel
            yum install -y gfortran python3-devel libaio-devel libcurl-devel

            # install openmp for alibaba clang 11
            yum install -b current -y libomp11-devel libomp11

            # install Intel MKL
            yum install -y ca-certificates
            yum-config-manager --add-repo https://yum.repos.intel.com/mkl/setup/intel-mkl.repo
            rpm --import https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
            yum install -y intel-mkl-64bit-2020.0-088

      
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error