name: Performance-arm

on:
  schedule:
    - cron: "01 08 * * 1-5" # UTC 08:01 every weekday
  workflow_dispatch: {}

jobs:
  performance:
    name: Performance-arm
    runs-on: ubuntu-22.04-arm
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Download Datasets
        run: bash ./scripts/download_annbench_datasets.sh
      - name: Install dependencies
        run:  sudo bash ./scripts/deps/install_deps_ubuntu.sh

      - name: Build test executables
        run: cmake -B build -S . -DDISABLE_SVE_FORCE=ON -DENABLE_TOOLS=ON -DCMAKE_BUILD_TYPE=Release &&cmake --build build -j6

      - name: Run Perf - Recall 90%, 95%, 99%
        run:  |
          ./build/tools/eval/eval_performance .github/perf-mini.yml
      - name: Send Report
        run:  |
          python3 scripts/perf_reports/dingding.py /tmp/github-perf.json || echo "send report to dingding failed"
