name: Performance-arm-generic

on:
  schedule:
    - cron: "01 08 * * 1-5" # UTC 08:01 every weekday
  workflow_dispatch: {}

jobs:
  performance:
    name: Performance-arm
    runs-on: ubuntu-22.04-arm
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Download Datasets
        run: bash ./scripts/download_annbench_datasets.sh
      - name: Install dependencies
        run:  sudo bash ./scripts/deps/install_deps_ubuntu.sh

      - name: Build test executables
        run: cmake -B build -S . -DDISABLE_NEON_FORCE=ON -DDISABLE_SVE_FORCE=ON -DENABLE_TOOLS=ON -DCMAKE_BUILD_TYPE=Release &&cmake --build build -j6

      - name: Run Perf - SIFT-fp32
        continue-on-error: true
        run: ./build/tools/eval/eval_performance .github/perf-mini-sift-fp32.yml
      - name: Run Perf - SIFT-fp16
        continue-on-error: true
        run: ./build/tools/eval/eval_performance .github/perf-mini-sift-fp16.yml
      - name: Run Perf - SIFT-bf16
        continue-on-error: true
        run: ./build/tools/eval/eval_performance .github/perf-mini-sift-bf16.yml
      - name: Run Perf - SIFT-sq8
        continue-on-error: true
        run: ./build/tools/eval/eval_performance .github/perf-mini-sift-sq8.yml
      - name: Run Perf - SIFT-sq8_uniform
        continue-on-error: true
        run: ./build/tools/eval/eval_performance .github/perf-mini-sift-sq8_uniform.yml
      - name: Run Perf - SIFT-sq4
        continue-on-error: true
        run: ./build/tools/eval/eval_performance .github/perf-mini-sift-sq4.yml
      - name: Run Perf - SIFT-sq4_uniform
        continue-on-error: true
        run: ./build/tools/eval/eval_performance .github/perf-mini-sift-sq4_uniform.yml
      - name: Run Perf - SIFT-pq
        continue-on-error: true
        run: ./build/tools/eval/eval_performance .github/perf-mini-sift-pq.yml
      - name: Run Perf - SIFT-pqfs
        continue-on-error: true
        run: ./build/tools/eval/eval_performance .github/perf-mini-sift-pqfs.yml
      - name: Run Perf - SIFT-rabitq
        continue-on-error: true
        run: ./build/tools/eval/eval_performance .github/perf-mini-sift-rabitq.yml
      - name: Send Report
        run:  |
          python3 scripts/perf_reports/dingding.py /tmp/github-perf.json || echo "send report to dingding failed"
