name: Performance

on:
  schedule:
    - cron: "01 08 * * 1-5" # UTC 08:01 every weekday
  workflow_dispatch: {}

jobs:
  performance:
    name: Performance
    runs-on: ubuntu-latest
    concurrency:
      group: performance-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    container:
      image: vsaglib/vsag:ci-x86
    env:
      PERF_DINGDING_ACCESS_TOKEN: ${{ secrets.PERF_DINGDING_ACCESS_TOKEN }}
      PERF_DINGDING_SERCRET: ${{ secrets.PERF_DINGDING_SERCRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Deps
        run: pip3 install -r ./scripts/perf_reports/requirements.txt
      - name: Download Datasets
        run: bash ./scripts/download_annbench_datasets.sh
      - name: Build Release
        run: make release
      - name: Run Perf - Recall 90%, 95%, 99%
        run:  |
          ./build-release/tools/eval/eval_performance .github/perf-mini.yml
      - name: Send Report
        run:  |
          python3 scripts/perf_reports/dingding.py /tmp/github-perf.json || echo "send report to dingding failed"
