name: VSAG Performance Test

# 触发工作流的事件
on:
  push:
    branches: [ main ]  # 当有代码推送到 main 分支时触发
  pull_request:
    branches: [ main ]  # 当有PR合并到 main 分支时触发
  workflow_dispatch:      # 允许手动触发

jobs:
  performance-analysis:
    runs-on: ubuntu-22.04-arm  # 使用最新的 Ubuntu Runner

    steps:
      # 第1步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第2步：安装依赖 (perf 工具)
      # 这是在 Runner 上准备环境的关键步骤
      - name: Install perf and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          build-essential \
          linux-tools-common \
          linux-tools-generic \
          linux-tools-$(uname -r) || sudo apt-get install -y linux-tools-5.15.0-1053-azure
          git clone --depth 1 https://github.com/brendangregg/FlameGraph.git
          sudo bash scripts/deps/install_deps_ubuntu.sh 
        
          pip install pandas matplotlib seaborn plotly kaleido
          echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid || true
          echo 0 | sudo tee /proc/sys/kernel/kptr_restrict || true

      # 第3步：运行您的性能测试脚本
      # 我们将您的脚本命名为 run_perf_tests.sh
      - name: Run Performance Test Script
        run: |
          # 赋予脚本执行权限
          chmod +x ./perf.sh
          # 使用 sudo 运行，因为 perf 需要 root 权限
          sudo ./perf.sh
    

      - name: Archive performance results
        run: |
          sudo tar -czvf performance_report.tar.gz perf_results
      

      # 第5步：上传性能测试数据
      - name: Change artifact ownership
        run: sudo chown runner:runner performance_report.tar.gz

      - name: Upload performance artifact
        uses: actions/upload-artifact@v4
        with:
          name: performance-report-${{ github.sha }}
          path: performance_report.tar.gz
          retention-days: 90
